"""Abstract LLM provider interface and concrete DeepSeek implementation.

Uses the OpenAI-compatible SDK to call DeepSeek's API.  The provider is
designed to be swapped at runtime via the :class:`LLMDispatcher`.
"""

from __future__ import annotations

import time
from typing import Any, Dict, Optional

from openai import OpenAI

from ai_service.config.settings import get_settings
from ai_service.utils.logger import logger


# ---------------------------------------------------------------------------
# Abstract base
# ---------------------------------------------------------------------------

class BaseLLMProvider:
    """Protocol for an LLM backend that the dispatcher can delegate to.

    Every concrete provider (DeepSeek, Qwen, OpenAI, Claude, …) must
    implement :meth:`generate`.
    """

    def generate(
        self,
        prompt: str,
        *,
        system_prompt: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        **kwargs: Any,
    ) -> str:
        """Send a prompt to the LLM and return the generated text.

        Parameters
        ----------
        prompt : str
            The user message / full prompt.
        system_prompt : str, optional
            An optional system-level instruction.
        temperature : float, optional
            Sampling temperature; falls back to the global setting.
        max_tokens : int, optional
            Max tokens in the response; falls back to the global setting.
        **kwargs
            Extra provider-specific parameters.

        Returns
        -------
        str
            The text generated by the model.

        Raises
        ------
        NotImplementedError
            Must be overridden by subclasses.
        """
        raise NotImplementedError


# ---------------------------------------------------------------------------
# DeepSeek provider (OpenAI-compatible)
# ---------------------------------------------------------------------------

class DeepSeekProvider(BaseLLMProvider):
    """Calls the DeepSeek API through the OpenAI SDK.

    Parameters
    ----------
    settings : Settings
        Application settings object injected by the caller.
    """

    def __init__(self) -> None:
        self._settings = get_settings()
        self._client = OpenAI(
            api_key=self._settings.DEEPSEEK_API_KEY,
            base_url=self._settings.BASE_URL,
            timeout=self._settings.LLM_TIMEOUT,
            max_retries=self._settings.LLM_MAX_RETRIES,
        )
        logger.info(
            "DeepSeekProvider initialised | base_url={} model={} timeout={}s",
            self._settings.BASE_URL,
            self._settings.MODEL_NAME,
            self._settings.LLM_TIMEOUT,
        )

    # ------------------------------------------------------------------
    def generate(
        self,
        prompt: str,
        *,
        system_prompt: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        **kwargs: Any,
    ) -> str:
        """Call the DeepSeek chat-completion endpoint.

        Parameters
        ----------
        prompt : str
            The user message.
        system_prompt : str, optional
            System-level instruction.
        temperature : float, optional
            Sampling temperature.
        max_tokens : int, optional
            Max tokens in the response.
        **kwargs
            Additional parameters forwarded to the OpenAI SDK.

        Returns
        -------
        str
            Text content of the model's response.

        Raises
        ------
        RuntimeError
            If the API returns an unexpected empty response.
        """
        messages = self._build_messages(prompt, system_prompt)
        temp = temperature if temperature is not None else self._settings.LLM_TEMPERATURE
        tokens = max_tokens if max_tokens is not None else self._settings.LLM_MAX_TOKENS

        logger.info(
            "LLM request | model={} temp={} max_tokens={} prompt_len={}",
            self._settings.MODEL_NAME,
            temp,
            tokens,
            len(prompt),
        )
        logger.debug("LLM prompt preview: {:.200}...", prompt)

        t0 = time.perf_counter()

        try:
            response = self._client.chat.completions.create(
                model=self._settings.MODEL_NAME,
                messages=messages,
                temperature=temp,
                max_tokens=tokens,
                **kwargs,
            )
        except Exception:
            logger.exception("LLM API call failed after {:.2f}s", time.perf_counter() - t0)
            raise

        elapsed = time.perf_counter() - t0

        if not response.choices:
            raise RuntimeError("LLM returned no choices")

        content = response.choices[0].message.content or ""
        usage = response.usage

        logger.info(
            "LLM response | elapsed={:.2f}s len={} "
            "prompt_tokens={} completion_tokens={} total_tokens={}",
            elapsed,
            len(content),
            usage.prompt_tokens if usage else "?",
            usage.completion_tokens if usage else "?",
            usage.total_tokens if usage else "?",
        )

        return content

    # ------------------------------------------------------------------
    @staticmethod
    def _build_messages(
        prompt: str,
        system_prompt: Optional[str] = None,
    ) -> list[Dict[str, str]]:
        """Build the message list for the chat-completion API.

        Parameters
        ----------
        prompt : str
            User message.
        system_prompt : str, optional
            System message placed first.

        Returns
        -------
        list[dict]
            OpenAI-format message list.
        """
        messages: list[Dict[str, str]] = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})
        return messages
