"""LLM Dispatcher — the single entry-point for all LLM calls.

Services never call a provider directly; they always go through
:class:`LLMDispatcher`, which delegates to the configured backend.
Swapping in a new model (Qwen, Llama, Claude, …) only requires
changing the provider — zero changes in business logic.
"""

from __future__ import annotations

from typing import Optional

from ai_service.llm.deepseek import BaseLLMProvider, DeepSeekProvider
from ai_service.utils.logger import logger


class LLMDispatcher:
    """Central dispatcher that routes prompts to the active LLM backend.

    The dispatcher owns a :class:`BaseLLMProvider` instance (injected or
    created by default) and exposes a single :meth:`generate` method.
    Every service depends on the dispatcher, *not* on a concrete provider.

    Parameters
    ----------
    provider : BaseLLMProvider, optional
        A pre-configured provider.  Defaults to :class:`DeepSeekProvider`.

    Examples
    --------
    >>> dispatcher = LLMDispatcher()
    >>> reply = dispatcher.generate("你好，请介绍一下自己")
    """

    def __init__(self, provider: Optional[BaseLLMProvider] = None) -> None:
        self._provider = provider or DeepSeekProvider()
        logger.info(
            "LLMDispatcher ready | provider={}",
            type(self._provider).__name__,
        )

    # ------------------------------------------------------------------
    def generate(
        self,
        prompt: str,
        *,
        system_prompt: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> str:
        """Generate text via the underlying provider.

        Parameters
        ----------
        prompt : str
            The full user prompt (after template rendering and context injection).
        system_prompt : str, optional
            Optional system-level message.
        temperature : float, optional
            Sampling temperature override.
        max_tokens : int, optional
            Max-tokens override.

        Returns
        -------
        str
            Raw text generated by the LLM.

        Raises
        ------
        RuntimeError
            Propagated from the underlying provider on failure.
        """
        logger.debug("Dispatching prompt len={} to {}", len(prompt), type(self._provider).__name__)
        return self._provider.generate(
            prompt,
            system_prompt=system_prompt,
            temperature=temperature,
            max_tokens=max_tokens,
        )

    # ------------------------------------------------------------------
    def swap_provider(self, provider: BaseLLMProvider) -> None:
        """Replace the current provider at runtime.

        Parameters
        ----------
        provider : BaseLLMProvider
            The new LLM backend to use for all subsequent calls.

        Examples
        --------
        >>> from some_future_module import QwenProvider
        >>> dispatcher.swap_provider(QwenProvider())
        """
        old = type(self._provider).__name__
        self._provider = provider
        logger.info("Provider swapped | {} → {}", old, type(provider).__name__)

    # ------------------------------------------------------------------
    @property
    def provider_name(self) -> str:
        """Return the class name of the current provider."""
        return type(self._provider).__name__
